# Generated by Django 2.2.4 on 2019-08-22 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True, verbose_name='название категории')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='MaterialUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True, verbose_name='единица измерения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'verbose_name': 'единица',
                'verbose_name_plural': 'единицы',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='материал')),
                ('short_desc', models.TextField(blank=True, max_length=160, null=True, verbose_name='краткое описание')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='текущее количество')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.MaterialCategory', verbose_name='категория')),
                ('units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.MaterialUnits', verbose_name='единица измерения')),
            ],
            options={
                'verbose_name': 'материал',
                'verbose_name_plural': 'материалы',
            },
        ),
    ]
