# Generated by Django 2.2.4 on 2019-08-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='count_full',
            field=models.PositiveIntegerField(default=0, verbose_name='минимальное количество'),
        ),
    ]
