# Generated by Django 2.2.4 on 2019-09-07 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_count_full'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Material', verbose_name='название')),
            ],
            options={
                'verbose_name': 'Экземляр материала',
                'verbose_name_plural': 'Экземляры',
            },
        ),
    ]
